/*
 * SPDX-FileCopyrightText: 2026 ESP-KVM contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * GENERATED by tools/mkfont.py - do not edit.
 *
 * The 19-tall font: the UEFI narrow font, what a firmware's own console
 * draws with, and so what a UEFI boot menu or setup screen is written in.
 * The bitmaps come from EDK2's standard narrow glyph table
 * (gUsStdNarrowGlyphData, Intel, BSD-2-Clause-Patent).
 *
 * Built from: uefi_hii_8x19.txt
 * 190 distinct bitmaps, sorted by hash for a binary search.
 */
#pragma once

#include "screentext_glyph.h"

#define SCREENTEXT_FONT_H19_HEIGHT 19
#define SCREENTEXT_FONT_H19_GLYPHS 190

static const screentext_glyph_t screentext_font_h19[SCREENTEXT_FONT_H19_GLYPHS] = {
    {0x017a5d5d, 0x0042}, /* B */
    {0x01888f8b, 0x0069}, /* i */
    {0x01b2bd2f, 0x0049}, /* I */
    {0x01ec5311, 0x00bb}, /* U+00BB */
    {0x02eff507, 0x0065}, /* e */
    {0x058630d5, 0x0079}, /* y */
    {0x05ab8a39, 0x0058}, /* X */
    {0x07096507, 0x00ba}, /* U+00BA */
    {0x0736b3ab, 0x0071}, /* q */
    {0x0a566389, 0x005f}, /* _ */
    {0x0aeda70f, 0x00c5}, /* U+00C5 */
    {0x0af2e8f1, 0x0031}, /* 1 */
    {0x0b609bbf, 0x006f}, /* o */
    {0x0bc89d17, 0x0076}, /* v */
    {0x0dd5a681, 0x00fb}, /* U+00FB */
    {0x0ec6d377, 0x0020}, /* U+0020 */
    {0x0fb9f8db, 0x00e3}, /* U+00E3 */
    {0x10822269, 0x00f7}, /* U+00F7 */
    {0x158b52d7, 0x007c}, /* | */
    {0x1837b015, 0x00e2}, /* U+00E2 */
    {0x1b320335, 0x004c}, /* L */
    {0x1bc5d137, 0x00a6}, /* U+00A6 */
    {0x1dca3285, 0x00ff}, /* U+00FF */
    {0x1e5ad345, 0x007a}, /* z */
    {0x1f979eb7, 0x003c}, /* < */
    {0x1fe2d82f, 0x007d}, /* } */
    {0x248e1b8d, 0x0078}, /* x */
    {0x25a20653, 0x00e9}, /* U+00E9 */
    {0x261d533f, 0x00df}, /* U+00DF */
    {0x263786a3, 0x00ec}, /* U+00EC */
    {0x26745dbb, 0x00d7}, /* U+00D7 */
    {0x2734507f, 0x0063}, /* c */
    {0x27ad39a7, 0x0045}, /* E */
    {0x292860dd, 0x0053}, /* S */
    {0x2946134f, 0x00db}, /* U+00DB */
    {0x2ca19f8b, 0x00f4}, /* U+00F4 */
    {0x2cb25e25, 0x00b2}, /* U+00B2 */
    {0x2d0877cf, 0x0070}, /* p */
    {0x2e42101f, 0x00de}, /* U+00DE */
    {0x305b4455, 0x00b3}, /* U+00B3 */
    {0x34cae767, 0x00cd}, /* U+00CD */
    {0x36bf8693, 0x00e6}, /* U+00E6 */
    {0x37100839, 0x004a}, /* J */
    {0x373222a9, 0x0040}, /* @ */
    {0x37bab831, 0x004b}, /* K */
    {0x3817c789, 0x00ad}, /* U+00AD */
    {0x3a4c7917, 0x005d}, /* ] */
    {0x3c69ae6d, 0x005e}, /* ^ */
    {0x3f146017, 0x003b}, /* ; */
    {0x3fbbbdbe, 0x00bc}, /* U+00BC */
    {0x4127ef3b, 0x003f}, /* ? */
    {0x43a21fff, 0x00ae}, /* U+00AE */
    {0x45ccff07, 0x0034}, /* 4 */
    {0x475359a3, 0x00ca}, /* U+00CA */
    {0x4755259d, 0x0072}, /* r */
    {0x4a3a3db9, 0x00f0}, /* U+00F0 */
    {0x4a50eb9b, 0x00d1}, /* U+00D1 */
    {0x505443a9, 0x00ac}, /* U+00AC */
    {0x50fc551f, 0x0035}, /* 5 */
    {0x51c099cb, 0x0023}, /* # */
    {0x53d5a141, 0x00c2}, /* U+00C2 */
    {0x57206a03, 0x00a1}, /* U+00A1 */
    {0x573b708d, 0x006d}, /* m */
    {0x58234825, 0x00c0}, /* U+00C0 */
    {0x5a38554f, 0x00b6}, /* U+00B6 */
    {0x5b195948, 0x00af}, /* U+00AF */
    {0x5bc4b31f, 0x00d0}, /* U+00D0 */
    {0x5c89a831, 0x0050}, /* P */
    {0x5e74927f, 0x0062}, /* b */
    {0x5ecbcbdf, 0x00ed}, /* U+00ED */
    {0x619d5737, 0x00a2}, /* U+00A2 */
    {0x634ae985, 0x00a5}, /* U+00A5 */
    {0x658acad9, 0x0052}, /* R */
    {0x663d7c85, 0x00f5}, /* U+00F5 */
    {0x664bb571, 0x00d2}, /* U+00D2 */
    {0x66a0f06d, 0x00a9}, /* U+00A9 */
    {0x678f96eb, 0x005a}, /* Z */
    {0x694e5853, 0x00b4}, /* U+00B4 */
    {0x6c5995ef, 0x00fe}, /* U+00FE */
    {0x6cfbf587, 0x00b1}, /* U+00B1 */
    {0x704905d3, 0x006a}, /* j */
    {0x733ad2be, 0x00be}, /* U+00BE */
    {0x758f73d9, 0x00c6}, /* U+00C6 */
    {0x765a0bbf, 0x00f8}, /* U+00F8 */
    {0x7793f0f9, 0x002b}, /* + */
    {0x78773247, 0x00bd}, /* U+00BD */
    {0x79195b57, 0x005b}, /* [ */
    {0x79910eab, 0x00da}, /* U+00DA */
    {0x7bf70c09, 0x002d}, /* - */
    {0x7cef1297, 0x0043}, /* C */
    {0x7f3c6b73, 0x00a7}, /* U+00A7 */
    {0x7f98e577, 0x003d}, /* = */
    {0x805845c7, 0x0057}, /* W */
    {0x84b2f81b, 0x00dc}, /* U+00DC */
    {0x85a187d3, 0x00ce}, /* U+00CE */
    {0x881cef05, 0x0047}, /* G */
    {0x885fa2e7, 0x0028}, /* ( */
    {0x8884c2b3, 0x00d9}, /* U+00D9 */
    {0x88b040db, 0x0021}, /* ! */
    {0x896c2bd7, 0x002e}, /* . */
    {0x8c69fa79, 0x00d3}, /* U+00D3 */
    {0x8ccb386f, 0x00f6}, /* U+00F6 */
    {0x8cd34467, 0x004d}, /* M */
    {0x8ce549bf, 0x00a4}, /* U+00A4 */
    {0x8d5ae48f, 0x007b}, /* { */
    {0x8f98e0b9, 0x00e1}, /* U+00E1 */
    {0x8febe8e1, 0x00fd}, /* U+00FD */
    {0x91fa067f, 0x005c}, /* \ */
    {0x96086857, 0x00eb}, /* U+00EB */
    {0x97017db7, 0x00e7}, /* U+00E7 */
    {0x97aa8517, 0x00c3}, /* U+00C3 */
    {0x98856f13, 0x00b8}, /* U+00B8 */
    {0x9a90dd89, 0x00e0}, /* U+00E0 */
    {0x9a94f34b, 0x006c}, /* l */
    {0x9ab38347, 0x00f3}, /* U+00F3 */
    {0x9bf306c3, 0x00bf}, /* U+00BF */
    {0x9c8b1f93, 0x00ea}, /* U+00EA */
    {0x9d04c68d, 0x0051}, /* Q */
    {0x9da476a9, 0x0074}, /* t */
    {0x9ea600b1, 0x00dd}, /* U+00DD */
    {0xa26d5cad, 0x00fa}, /* U+00FA */
    {0xa27f7f43, 0x0054}, /* T */
    {0xa38ca0e1, 0x0061}, /* a */
    {0xa3f96eff, 0x00ab}, /* U+00AB */
    {0xa6f11bff, 0x002f}, /* / */
    {0xa8523355, 0x0077}, /* w */
    {0xa988dc47, 0x003a}, /* : */
    {0xac5ed67d, 0x00a3}, /* U+00A3 */
    {0xac9b6707, 0x00f1}, /* U+00F1 */
    {0xacf2c87d, 0x0033}, /* 3 */
    {0xada13195, 0x006b}, /* k */
    {0xafe2166d, 0x0056}, /* V */
    {0xb0728177, 0x0026}, /* & */
    {0xb08e4e7d, 0x0038}, /* 8 */
    {0xb0a0269b, 0x00ef}, /* U+00EF */
    {0xb3068df9, 0x00e4}, /* U+00E4 */
    {0xb351a835, 0x0055}, /* U */
    {0xb48693ab, 0x00c4}, /* U+00C4 */
    {0xb521cd61, 0x003e}, /* > */
    {0xb78e31f5, 0x00c1}, /* U+00C1 */
    {0xbc92f70d, 0x006e}, /* n */
    {0xbdc135b1, 0x00a8}, /* U+00A8 */
    {0xbe91704b, 0x0059}, /* Y */
    {0xc0d6157d, 0x0064}, /* d */
    {0xc20cf69f, 0x00b7}, /* U+00B7 */
    {0xc281f2fb, 0x0032}, /* 2 */
    {0xc3441817, 0x00aa}, /* U+00AA */
    {0xc530353d, 0x0036}, /* 6 */
    {0xc6d9f2bf, 0x004e}, /* N */
    {0xc74c419b, 0x0073}, /* s */
    {0xc82e4b4b, 0x00d5}, /* U+00D5 */
    {0xc850f135, 0x0075}, /* u */
    {0xca0c6055, 0x007e}, /* ~ */
    {0xcc1475a1, 0x00ee}, /* U+00EE */
    {0xcc569a3f, 0x00c7}, /* U+00C7 */
    {0xcce29af7, 0x00f2}, /* U+00F2 */
    {0xcd37c85d, 0x0067}, /* g */
    {0xd0d1837b, 0x0022}, /* " */
    {0xd309581f, 0x002c}, /* , */
    {0xd55d34ed, 0x00fc}, /* U+00FC */
    {0xd568e00f, 0x0044}, /* D */
    {0xd6522c79, 0x002a}, /* * */
    {0xd8ed753f, 0x004f}, /* O */
    {0xda2ad2b5, 0x00b5}, /* U+00B5 */
    {0xdb25547d, 0x00f9}, /* U+00F9 */
    {0xdcafdc6d, 0x0041}, /* A */
    {0xdd7e5fd7, 0x00cf}, /* U+00CF */
    {0xde9a724f, 0x00e8}, /* U+00E8 */
    {0xdf2a1348, 0x0066}, /* f */
    {0xe1951e0d, 0x00d4}, /* U+00D4 */
    {0xe25512fd, 0x0037}, /* 7 */
    {0xe2ee5d45, 0x00e5}, /* U+00E5 */
    {0xe6302a9d, 0x0068}, /* h */
    {0xe78a4e2f, 0x0025}, /* % */
    {0xe9490f77, 0x0029}, /* ) */
    {0xe995a1ef, 0x00cc}, /* U+00CC */
    {0xec601ecf, 0x0027}, /* ' */
    {0xed5da3cf, 0x0030}, /* 0 */
    {0xedb60a87, 0x00cb}, /* U+00CB */
    {0xede5609f, 0x0048}, /* H */
    {0xefc1a259, 0x0046}, /* F */
    {0xf162d667, 0x00c8}, /* U+00C8 */
    {0xf279745b, 0x00b9}, /* U+00B9 */
    {0xf390d489, 0x00d6}, /* U+00D6 */
    {0xf41884f7, 0x00c9}, /* U+00C9 */
    {0xf9d506d1, 0x0039}, /* 9 */
    {0xfa74857d, 0x0024}, /* $ */
    {0xfb1edc6f, 0x0060}, /* ` */
    {0xfc62c827, 0x00d8}, /* U+00D8 */
    {0xfed3740f, 0x00b0}, /* U+00B0 */
};
